---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dandydev
  namespace: flux-system
spec:
  interval: 30m
  url: https://dandydeveloper.github.io/charts
  timeout: 2m
