---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kometa
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "0 */6 * * *"
        pod:
          restartPolicy: OnFailure
        containers:
          main:
            image:
              repository: kometateam/kometa
              tag: v2.2.1
            env:
              KOMETA_READ_ONLY_CONFIG: "true"
              KOMETA_RUN: "true"
    service:
      main:
        controller: main
        enabled: false
    persistence:
      config:
        existingClaim: kometa
      config-secret:
        enabled: true
        type: secret
        name: plex-meta-manager-config
        advancedMounts:
          main:
            main:
              - subPath: config.yaml
                path: /config/config.yml
      collections-dir:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /collections
      collections:
        enabled: true
        type: configMap
        name: plex-meta-manager-collections
        advancedMounts:
          main:
            main:
            - subPath: charts.yaml
              path: /collections/movies-charts.yaml
              readOnly: true
            - subPath: movies.yaml
              path: /collections/movies-movies.yaml
              readOnly: true
            - subPath: holidays.yaml
              path: /collections/movies-holidays.yaml
              readOnly: true
            - subPath: studios.yaml
              path: /collections/movies-studios.yaml
              readOnly: true
            - subPath: tv-charts.yaml
              path: /collections/tv-charts.yaml
              readOnly: true
