---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6
  primaryUpdateStrategy: unsupervised
  storage:
    size: 25Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg-postgres-superuser
  bootstrap:
    recovery:
      source: &previous-cluster postgres-v1
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: http://minio.storage.svc:9000
      serverName: postgres-v2 # when a restore is needed, increment this and change 'previousCluster'
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-postgres-s3
          key: S3_ACCESS_KEY
        secretAccessKey:
          name: cloudnative-pg-postgres-s3
          key: S3_SECRET_KEY
  externalClusters:
    - name: *previous-cluster
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: s3://postgresql/
        endpointURL: http://minio.storage.svc:9000
        s3Credentials:
          accessKeyId:
            name: cloudnative-pg-postgres-s3
            key: S3_ACCESS_KEY
          secretAccessKey:
            name: cloudnative-pg-postgres-s3
            key: S3_SECRET_KEY
