---
######################################################
#                Chart Collections                   #
######################################################
collections:
  Plex Popular:
    sync_mode: sync
    collection_order: custom
    tautulli_popular:
      list_days: 30
      list_size: 10
    summary: Movies Popular on Plex
  Top Rated:
    template: { name: Chart, num: 4 }
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=250/
    tmdb_top_rated: 250
    summary: Top Rated Movies across the internet
  Oscars:
    imdb_list:
      list_id: https://www.imdb.com/search/title/?title_type=feature,documentary&groups=oscar_winner
    summary: Oscar Winning Movies
  # 2025 Oscar Nominees:
  #   imdb_list:
  #     list_id: ls597676647
  #   summary: 2025 Oscar Nominees
  2026 Oscar Nominees:
    imdb_list:
      list_id: ls4102637648
    summary: 2026 Oscar Nominees
